name: Todo Build

on:
  pull_request:
    branches: [develop, main, senpai]
    paths:
      - ".github/workflows/build.yml"
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

jobs:
  test:
    runs-on: ubuntu-22.04

    defaults:
      run:
        working-directory: ./

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js LTS
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: "npm"
          cache-dependency-path: pnpm-lock.json

      - name: Install deps
        run: npm ci

      - name: Run tests
        run: npm run build
